# Generated by Django 4.2.3 on 2023-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riderapp', '0002_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
